name: starting DB
on:
  push:
    branches: ["TodoBackTesting","master"]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop 

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql password: ${{ secrets.DB_PASSWORD }}
          mysql user: ${{ secrets.DB_USER }}
  
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file todolist/pom.xml
